### PR TITLE
Fill.arc

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Based on `Lines.arc`.
~~I didn't know `Lines.arc` existed until now.~~

arc

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Btw why does `Lines.arc` not use the `beginLine()`/`linePoint()`/`endLine()` things?

**Comment by Anuken** [comment]
I believe it was written before those methods existed.

**Comment by MEEPofFaith** [comment]
> I believe it was written before those methods existed.

Actually, if you check the v135 tag, `Lines.arc` does not exist and the poly line stuff does.

**Comment by Anuken** [comment]
`arc` is just `swirl` renamed.

**Comment by MEEPofFaith** [comment]
oh

**Pull request merged**
