### PR TITLE
Make various Seq methods return itself

### PR DESCRIPTION
**Pull request by buthed010203**
This is useful for things such as shuffling in place, I made a few of the javadocs more consistent but I'm on mobile so I don't have find and replace and didn't want to look through 1110 lines to correct them all.

### CODE REVIEW

**Comment by Anuken** [comment]
I was forced to revert this, as it affects the java API and causes mods to crash.

**Comment by buthed010203** [comment]
Damn, thats annoying. I've had problems with this myself when changing the return types of certain methods

**Comment by Anuken** [comment]
It's not that bad, you can still do `new Seq<Object>().with(Seq::sort)`, replacing sort with addAll or other operations.

**Comment by buthed010203** [comment]
That sounds like more work than just splitting code across two lines, the case where i changed a return type was on chatfrag.addMessage() so i ended up just creating an overload. I suppose a different solution would be a kotlin extension function called sortandreturn or whatever which would sort and return itself. The downside here is that it wouldnt be accessible from java files through seq.sortandreturn() but would instead be something like UtilsKt.sortandreturn(seq) which isnt fun

**Pull request merged**
