### PR TITLE
Lines.ellipse

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/133877598-b5a9a7e6-30fb-4a08-8302-9e27c3c9c8e5.mp4

### CODE REVIEW

**Comment by KayWasTaken** [comment]
certain people will do certain nsfw things with this

**Comment by MEEPofFaith** [comment]
w h a t

**Comment by summetdev** [comment]
You forgot to *import static ...Mathf*

**Comment by MEEPofFaith** [comment]
Why not use polyline?

**Comment by Anuken** [comment]
Why not, meep?

**Comment by MEEPofFaith** [comment]
That's a good question.

**Pull request merged**
