### PR TITLE
Fix ApplicationListeners being skipped

### PR DESCRIPTION
**Pull request by phinner**
Basically, when a `ApplicationListener` uses `Application#removeListener` while the application is iterating over the listener seq, the next listener in the iteration is skipped.

This issue hasn't been noticed for so long since the only use of it is within the `dispose` of `Timer.TimerThread`, and that it runs before listeners that doesn't use `dispose`.

But in BE servers, it prevents my plugins from exiting since `Timer` is used early by `BeControl`, running before my [plugin shutdown listener](https://github.com/xpdustry/distributor/blob/ee9f10e5d53345784e6782c4e7a8ea6f697cc54a/distributor-api/src/main/java/fr/xpdustry/distributor/api/plugin/AbstractMindustryPlugin.java#L48-L66) thus skipping it.

The fix is simply replacing the removed listener by an empty one.

### CODE REVIEW

**Comment by Anuken** [comment]
Isn't this kind of a memory leak? If you call add and remove in a loop, it will OOM eventually.

**Comment by phinner** [comment]
> Isn't this kind of a memory leak? If you call add and remove in a loop, it will OOM eventually.

Well, my reasoning was since it is used rarely and also to avoid refactoring the whole thing, it would do the trick, but now that you mention it... I'll get back to it.

**Comment by phinner** [comment]
Okay, if you don't mind making `removeListener` and `addListener`, what about this ?

```java
public abstract class AbstractApplication implements Application{

    protected final Seq<ApplicationListener> listeners = new Seq<>();
    protected boolean runningListeners = false;
    protected final Seq<ApplicationListener> removing = new Seq<>();

    @Override
    public Seq<ApplicationListener> getListeners(){
        return listeners;
    }

    @Override
    public void addListener(ApplicationListener listener){
        synchronized (listeners){
            listeners.add(listener);
        }
    }

    @Override
    public void removeListener(ApplicationListener listener){
        synchronized (listeners){
            if (runningListeners) removing.add(listener);
            else listeners.remove(listener);
        }
    }

    @Override
    public void forEachListener(Cons<ApplicationListener> cons){
        synchronized(listeners){
            runningListeners = true;
            try{
                for(ApplicationListener listener : listeners){
                    if(removing.contains(listener)) continue;
                    cons.get(listener);
                }
            }finally{
                runningListeners = false;
            }
            listeners.removeAll(removing);
            removing.clear();
        }
    }
}
```

The `forEachListener` makes sure no funny business occurs when one want to use the listeners.

**Comment by phinner** [comment]
Looks like I made things too complicated again, the solution was simply removing the listener when it's guaranteed the others are not used.

**Pull request merged**
