### PR TITLE
enable VT100 in windows for colored text

### PR DESCRIPTION
**Pull request by ZetaMap**
all is explain in file changes

### CODE REVIEW

**Comment by Anuken** [comment]
This doesn't seem like something Arc should do at all. Running registry commands in a utility class is too much, and color codes aren't particularly significant to begin with. I am almost certain this would break someone's setup or have unforeseen consequences.

**Comment by ZetaMap** [comment]
o yea sorry for compilation error, I forgot to import class and I had in mind the typing of c++ which is less demanding

**Comment by ZetaMap** [comment]
so i close the PR, you reject this?

**Comment by Anuken** [comment]
Yes, I'm not prepared to deal with potential issues just for color codes (especially with a completely untested PR.)

**Pull request closed without merging**
